services:
  - type: web
    name: file-forge-converter
    env: node
    buildCommand: |
      npm install -g npm@latest
      npm install --prefer-offline --no-audit
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
